#!/usr/bin/env bash
#
# Regenerate the installed-app inventory.
#
#   ./macos/inventory.sh              print a table
#   ./macos/inventory.sh --brewfile   print Brewfile lines for apps that have casks
#
# Reads /Applications, detects App Store installs by their _MASReceipt, and
# matches each app against the Homebrew cask catalog by the app name the cask
# actually installs. Requires network for the cask catalog (cached 24h).
#
# This is a REPORTING tool. It never installs anything. Which apps come back
# after a rebuild is a decision worth making at rebuild time — tastes change,
# apps get abandoned, and a stale auto-installer is worse than no list at all.
#
# The generated inventory is personal (it enumerates your licensed software),
# so keep the output out of a public repo.

set -e

CACHE="${TMPDIR:-/tmp}/homebrew-cask-catalog.json"
MODE="${1:-table}"

# Refresh the cask catalog if missing or older than a day
if [[ ! -f "$CACHE" ]] || [[ -n "$(find "$CACHE" -mtime +1 2>/dev/null)" ]]; then
    echo "Fetching Homebrew cask catalog..." >&2
    curl -sS --max-time 60 https://formulae.brew.sh/api/cask.json -o "$CACHE"
fi

python3 - "$CACHE" "$MODE" <<'PYEOF'
import json, pathlib, sys

cache, mode = sys.argv[1], sys.argv[2]
casks = json.load(open(cache))

# A cask's token is not its app name — match on the .app it actually installs.
app2cask = {}
for c in casks:
    for art in c.get("artifacts") or []:
        if isinstance(art, dict):
            for a in art.get("app") or []:
                if isinstance(a, str):
                    app2cask.setdefault(a.lower(), []).append(c["token"])

rows = []
for p in sorted(pathlib.Path("/Applications").iterdir()):
    if p.suffix != ".app":
        continue
    mas = (p / "Contents/_MASReceipt").is_dir()
    # Prefer the shortest token: "firefox" over "firefox@beta"
    tokens = sorted(app2cask.get(p.name.lower(), []), key=len)
    rows.append((p.stem, "AppStore" if mas else "direct", tokens))

if mode == "--brewfile":
    print("# Generated by macos/inventory.sh — review before use.")
    print("# Apps with no cask are listed at the bottom as comments.")
    print()
    for name, src, tokens in rows:
        if tokens:
            print(f'cask "{tokens[0]}"   # {name}')
    print()
    print("# No cask available — App Store (needs `mas`) or manual download:")
    for name, src, tokens in rows:
        if not tokens:
            print(f"#   {name}  ({src})")
else:
    print(f"{'APP':<28} {'SOURCE':<9} CASK")
    print("-" * 70)
    for name, src, tokens in rows:
        print(f"{name:<28} {src:<9} {tokens[0] if tokens else '—'}")
    n_mas = sum(1 for r in rows if r[1] == "AppStore")
    n_cask = sum(1 for r in rows if r[2])
    print(f"\n{len(rows)} apps | {n_mas} App Store | {n_cask} available as casks")
PYEOF
